plugins {
  id 'java-library'
  id 'jacoco'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

jar {
  from {
    configurations.runtimeClasspath.filter{ it.exists() }.collect{ it.isDirectory() ? it : zipTree(it) }
  } {
    exclude 'META-INF/LICENSE.txt', 'META-INF/NOTICE.txt'
  }

  // The following line is necessary because fat jars are not the default.
  // Hence we need to explicitly declare that we need these other jars,
  // in addition to declaring we need to compile against these projects.
  dependsOn ':streamline:jar'
  dependsOn ':contrib:jar'
}

test {
  useJUnitPlatform()
  testLogging {
    exceptionFormat = 'full'
  }
}

jacocoTestReport {
  dependsOn test
  reports {
    xml.required = true
  }
}

dependencies {
  annotationProcessor project(':merlin-framework-processor')

  implementation project(':streamline')


  testImplementation project(':merlin-framework-junit')
  testImplementation 'org.assertj:assertj-core:3.23.1'

  testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.8.2'

  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

