package gov.nasa.jpl.aerie.contrib.streamline.modeling.piecewise.monads;

import gov.nasa.jpl.aerie.contrib.streamline.modeling.piecewise.Profile;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

/**
 * {@link Profile} monad
 */
public final class ProfileMonad {
    private ProfileMonad() {}

    public static <A> Profile<A> pure(A a) {
        return Profile.constant(a);
    }

    public static <A, B> Profile<B> apply(Profile<A> a, Profile<Function<A, B>> f) {
        return a.apply(f);
    }

    public static <A> Profile<A> join(Profile<Profile<A>> a) {
        return Profile.join(a);
    }

    // GENERATED CODE START
    // Supplemental methods generated by generate_monad_methods.py on 2025-04-24.
    
    public static <A, B> Function<Profile<A>, Profile<B>> apply(Profile<Function<A, B>> f) {
      return a -> apply(a, f);
    }
    
    public static <A, B> Profile<B> map(Profile<A> a, Function<A, B> f) {
      return apply(a, pure(f));
    }
    
    public static <A, B> Function<Profile<A>, Profile<B>> map(Function<A, B> f) {
      return apply(pure(f));
    }
    
    public static <A, B> Profile<B> bind(Profile<A> a, Function<A, Profile<B>> f) {
      return join(map(a, f));
    }
    
    public static <A, B> Function<Profile<A>, Profile<B>> bind(Function<A, Profile<B>> f) {
      return a -> bind(a, f);
    }
    
    public static <A, B, Result> Profile<Result> map(Profile<A> a, Profile<B> b, BiFunction<A, B, Result> function) {
      return map(a, b, curry(function));
    }
    
    public static <A, B, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Function<A, Function<B, Result>> function) {
      return apply(b, map(a, function));
    }
    
    public static <A, B, Result> BiFunction<Profile<A>, Profile<B>, Profile<Result>> map(BiFunction<A, B, Result> function) {
      return (a, b) -> map(a, b, function);
    }
    
    public static <A, B, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, BiFunction<A, B, Profile<Result>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Function<A, Function<B, Profile<Result>>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> BiFunction<Profile<A>, Profile<B>, Profile<Result>> bind(BiFunction<A, B, Profile<Result>> function) {
      return (a, b) -> bind(a, b, function);
    }
    
    public static <A, B, C, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, TriFunction<A, B, C, Result> function) {
      return map(a, b, c, curry(function));
    }
    
    public static <A, B, C, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Function<A, Function<B, Function<C, Result>>> function) {
      return apply(c, map(a, b, function));
    }
    
    public static <A, B, C, Result> TriFunction<Profile<A>, Profile<B>, Profile<C>, Profile<Result>> map(TriFunction<A, B, C, Result> function) {
      return (a, b, c) -> map(a, b, c, function);
    }
    
    public static <A, B, C, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, TriFunction<A, B, C, Profile<Result>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Function<A, Function<B, Function<C, Profile<Result>>>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> TriFunction<Profile<A>, Profile<B>, Profile<C>, Profile<Result>> bind(TriFunction<A, B, C, Profile<Result>> function) {
      return (a, b, c) -> bind(a, b, c, function);
    }
    
    public static <A, B, C, D, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Function4<A, B, C, D, Result> function) {
      return map(a, b, c, d, curry(function));
    }
    
    public static <A, B, C, D, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
      return apply(d, map(a, b, c, function));
    }
    
    public static <A, B, C, D, Result> Function4<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<Result>> map(Function4<A, B, C, D, Result> function) {
      return (a, b, c, d) -> map(a, b, c, d, function);
    }
    
    public static <A, B, C, D, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Function4<A, B, C, D, Profile<Result>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Function<A, Function<B, Function<C, Function<D, Profile<Result>>>>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> Function4<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<Result>> bind(Function4<A, B, C, D, Profile<Result>> function) {
      return (a, b, c, d) -> bind(a, b, c, d, function);
    }
    
    public static <A, B, C, D, E, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Function5<A, B, C, D, E, Result> function) {
      return map(a, b, c, d, e, curry(function));
    }
    
    public static <A, B, C, D, E, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
      return apply(e, map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<Result>> map(Function5<A, B, C, D, E, Result> function) {
      return (a, b, c, d, e) -> map(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Function5<A, B, C, D, E, Profile<Result>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Profile<Result>>>>>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<Result>> bind(Function5<A, B, C, D, E, Profile<Result>> function) {
      return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, F, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Function6<A, B, C, D, E, F, Result> function) {
      return map(a, b, c, d, e, f, curry(function));
    }
    
    public static <A, B, C, D, E, F, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
      return apply(f, map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
      return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Function6<A, B, C, D, E, F, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Profile<Result>>>>>>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<Result>> bind(Function6<A, B, C, D, E, F, Profile<Result>> function) {
      return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
      return map(a, b, c, d, e, f, g, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
      return apply(g, map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
      return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Function7<A, B, C, D, E, F, G, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Profile<Result>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<Result>> bind(Function7<A, B, C, D, E, F, G, Profile<Result>> function) {
      return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
      return map(a, b, c, d, e, f, g, h, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
      return apply(h, map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
      return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Function8<A, B, C, D, E, F, G, H, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Profile<Result>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<Result>> bind(Function8<A, B, C, D, E, F, G, H, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
      return apply(i, map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Function9<A, B, C, D, E, F, G, H, I, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Profile<Result>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
      return apply(j, map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Profile<Result>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
      return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Profile<Result>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
      return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Profile<Result>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
      return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Profile<Result>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
      return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Profile<Result>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
      return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Profile<Result>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
      return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Profile<Result>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
      return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Profile<Result>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
      return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Profile<Result>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
      return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<S>, Profile<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Profile<Result>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<S>, Profile<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Profile<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Profile<Result> map(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Profile<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
      return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<S>, Profile<T>, Profile<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Profile<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Profile<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Profile<Result> bind(Profile<A> a, Profile<B> b, Profile<C> c, Profile<D> d, Profile<E> e, Profile<F> f, Profile<G> g, Profile<H> h, Profile<I> i, Profile<J> j, Profile<K> k, Profile<L> l, Profile<M> m, Profile<N> n, Profile<O> o, Profile<P> p, Profile<Q> q, Profile<R> r, Profile<S> s, Profile<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Profile<Result>>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Profile<A>, Profile<B>, Profile<C>, Profile<D>, Profile<E>, Profile<F>, Profile<G>, Profile<H>, Profile<I>, Profile<J>, Profile<K>, Profile<L>, Profile<M>, Profile<N>, Profile<O>, Profile<P>, Profile<Q>, Profile<R>, Profile<S>, Profile<T>, Profile<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Profile<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    // GENERATED CODE END
}
