package gov.nasa.jpl.aerie.contrib.streamline.modeling.piecewise.monads;

import gov.nasa.jpl.aerie.contrib.streamline.core.ErrorCatching;
import gov.nasa.jpl.aerie.contrib.streamline.core.Expiring;
import gov.nasa.jpl.aerie.contrib.streamline.core.Resource;
import gov.nasa.jpl.aerie.contrib.streamline.core.ThinResource;
import gov.nasa.jpl.aerie.contrib.streamline.core.monads.DynamicsMonad;
import gov.nasa.jpl.aerie.contrib.streamline.core.monads.ResourceMonad;
import gov.nasa.jpl.aerie.contrib.streamline.core.monads.ThinResourceMonad;
import gov.nasa.jpl.aerie.contrib.streamline.modeling.piecewise.Profile;
import gov.nasa.jpl.aerie.contrib.streamline.modeling.piecewise.ProfileResource;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.debugging.Dependencies.addDependency;
import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

// TODO: Add in profiling like in ResourceMonad

public final class ProfileResourceMonad {
    private ProfileResourceMonad() {}

    public static <A> ProfileResource<A> pure(A a) {
        return ThinResourceMonad.pure(ProfileDynamicsMonad.pure(a))::getDynamics;
    }

    public static <A, B> ProfileResource<B> apply(ProfileResource<A> a, ProfileResource<Function<A, B>> f) {
        ProfileResource<B> result = ThinResourceMonad.apply(a, ThinResourceMonad.map(f, ProfileDynamicsMonad::apply))::getDynamics;
        addDependency(result, a);
        addDependency(result, f);
        return result;
    }

    private static <A> ThinResource<ErrorCatching<Profile<A>>> distribute(ErrorCatching<Profile<ThinResource<A>>> a) {
        return () -> ProfileDynamicsMonad.map(a, ThinResource::getDynamics);
    }

    public static <A> ProfileResource<A> join(ProfileResource<ProfileResource<A>> a) {
        // Perform a trivial down-conversion to the base ThinResource types, to expose the Dynamics wrappers in the type signature.
        ThinResource<ErrorCatching<Profile<ThinResource<ErrorCatching<Profile<A>>>>>> a$ = map(a, $ -> $);
        // Then use distributivity and basic joins to collapse the type.
        // The ::getDynamics at the end up-converts back to Resource, from ThinResource
        ProfileResource<A> result = ThinResourceMonad.map(ThinResourceMonad.join(ThinResourceMonad.map(a$, ProfileResourceMonad::distribute)), ProfileDynamicsMonad::join)::getDynamics;
        addDependency(result, a);
        return result;
    }

    // TODO: Efficient reduce operators
    // TODO: Extra pure operators

    // GENERATED CODE START
    // Supplemental methods generated by generate_monad_methods.py on 2025-04-24.
    
    public static <A, B> Function<ProfileResource<A>, ProfileResource<B>> apply(ProfileResource<Function<A, B>> f) {
      return a -> apply(a, f);
    }
    
    public static <A, B> ProfileResource<B> map(ProfileResource<A> a, Function<A, B> f) {
      return apply(a, pure(f));
    }
    
    public static <A, B> Function<ProfileResource<A>, ProfileResource<B>> map(Function<A, B> f) {
      return apply(pure(f));
    }
    
    public static <A, B> ProfileResource<B> bind(ProfileResource<A> a, Function<A, ProfileResource<B>> f) {
      return join(map(a, f));
    }
    
    public static <A, B> Function<ProfileResource<A>, ProfileResource<B>> bind(Function<A, ProfileResource<B>> f) {
      return a -> bind(a, f);
    }
    
    public static <A, B, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, BiFunction<A, B, Result> function) {
      return map(a, b, curry(function));
    }
    
    public static <A, B, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, Function<A, Function<B, Result>> function) {
      return apply(b, map(a, function));
    }
    
    public static <A, B, Result> BiFunction<ProfileResource<A>, ProfileResource<B>, ProfileResource<Result>> map(BiFunction<A, B, Result> function) {
      return (a, b) -> map(a, b, function);
    }
    
    public static <A, B, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, BiFunction<A, B, ProfileResource<Result>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, Function<A, Function<B, ProfileResource<Result>>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> BiFunction<ProfileResource<A>, ProfileResource<B>, ProfileResource<Result>> bind(BiFunction<A, B, ProfileResource<Result>> function) {
      return (a, b) -> bind(a, b, function);
    }
    
    public static <A, B, C, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, TriFunction<A, B, C, Result> function) {
      return map(a, b, c, curry(function));
    }
    
    public static <A, B, C, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, Function<A, Function<B, Function<C, Result>>> function) {
      return apply(c, map(a, b, function));
    }
    
    public static <A, B, C, Result> TriFunction<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<Result>> map(TriFunction<A, B, C, Result> function) {
      return (a, b, c) -> map(a, b, c, function);
    }
    
    public static <A, B, C, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, TriFunction<A, B, C, ProfileResource<Result>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, Function<A, Function<B, Function<C, ProfileResource<Result>>>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> TriFunction<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<Result>> bind(TriFunction<A, B, C, ProfileResource<Result>> function) {
      return (a, b, c) -> bind(a, b, c, function);
    }
    
    public static <A, B, C, D, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, Function4<A, B, C, D, Result> function) {
      return map(a, b, c, d, curry(function));
    }
    
    public static <A, B, C, D, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
      return apply(d, map(a, b, c, function));
    }
    
    public static <A, B, C, D, Result> Function4<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<Result>> map(Function4<A, B, C, D, Result> function) {
      return (a, b, c, d) -> map(a, b, c, d, function);
    }
    
    public static <A, B, C, D, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, Function4<A, B, C, D, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, Function<A, Function<B, Function<C, Function<D, ProfileResource<Result>>>>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> Function4<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<Result>> bind(Function4<A, B, C, D, ProfileResource<Result>> function) {
      return (a, b, c, d) -> bind(a, b, c, d, function);
    }
    
    public static <A, B, C, D, E, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, Function5<A, B, C, D, E, Result> function) {
      return map(a, b, c, d, e, curry(function));
    }
    
    public static <A, B, C, D, E, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
      return apply(e, map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<Result>> map(Function5<A, B, C, D, E, Result> function) {
      return (a, b, c, d, e) -> map(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, Function5<A, B, C, D, E, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, ProfileResource<Result>>>>>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<Result>> bind(Function5<A, B, C, D, E, ProfileResource<Result>> function) {
      return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, F, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, Function6<A, B, C, D, E, F, Result> function) {
      return map(a, b, c, d, e, f, curry(function));
    }
    
    public static <A, B, C, D, E, F, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
      return apply(f, map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
      return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, Function6<A, B, C, D, E, F, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, ProfileResource<Result>>>>>>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<Result>> bind(Function6<A, B, C, D, E, F, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
      return map(a, b, c, d, e, f, g, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
      return apply(g, map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
      return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, Function7<A, B, C, D, E, F, G, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, ProfileResource<Result>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<Result>> bind(Function7<A, B, C, D, E, F, G, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
      return map(a, b, c, d, e, f, g, h, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
      return apply(h, map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
      return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, Function8<A, B, C, D, E, F, G, H, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, ProfileResource<Result>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<Result>> bind(Function8<A, B, C, D, E, F, G, H, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
      return apply(i, map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, Function9<A, B, C, D, E, F, G, H, I, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, ProfileResource<Result>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
      return apply(j, map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, Function10<A, B, C, D, E, F, G, H, I, J, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, ProfileResource<Result>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
      return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, ProfileResource<Result>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
      return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, ProfileResource<Result>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
      return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, ProfileResource<Result>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
      return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, ProfileResource<Result>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
      return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, ProfileResource<Result>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
      return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, ProfileResource<Result>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
      return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, ProfileResource<Result>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
      return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, ProfileResource<Result>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
      return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<S>, ProfileResource<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, ProfileResource<Result>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<S>, ProfileResource<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, ProfileResource<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProfileResource<Result> map(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, ProfileResource<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
      return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<S>, ProfileResource<T>, ProfileResource<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, ProfileResource<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ProfileResource<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProfileResource<Result> bind(ProfileResource<A> a, ProfileResource<B> b, ProfileResource<C> c, ProfileResource<D> d, ProfileResource<E> e, ProfileResource<F> f, ProfileResource<G> g, ProfileResource<H> h, ProfileResource<I> i, ProfileResource<J> j, ProfileResource<K> k, ProfileResource<L> l, ProfileResource<M> m, ProfileResource<N> n, ProfileResource<O> o, ProfileResource<P> p, ProfileResource<Q> q, ProfileResource<R> r, ProfileResource<S> s, ProfileResource<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, ProfileResource<Result>>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ProfileResource<A>, ProfileResource<B>, ProfileResource<C>, ProfileResource<D>, ProfileResource<E>, ProfileResource<F>, ProfileResource<G>, ProfileResource<H>, ProfileResource<I>, ProfileResource<J>, ProfileResource<K>, ProfileResource<L>, ProfileResource<M>, ProfileResource<N>, ProfileResource<O>, ProfileResource<P>, ProfileResource<Q>, ProfileResource<R>, ProfileResource<S>, ProfileResource<T>, ProfileResource<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ProfileResource<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    // GENERATED CODE END
}
