package gov.nasa.jpl.aerie.contrib.streamline.modeling.random.monads;

import gov.nasa.jpl.aerie.contrib.streamline.modeling.random.ProbabilityDistribution;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

// Isomorphic to ThinResourceMonad, as both are just a reader monad.

/**
 * Monad A -> ProbabilityDistribution&lt;A&gt;.
 * This monad describes how to derive one distribution as a function of others.
 */
public final class ProbabilityDistributionMonad {
    private ProbabilityDistributionMonad() {}

    public static <A> ProbabilityDistribution<A> pure(A a) {
        return () -> a;
    }

    public static <A, B> ProbabilityDistribution<B> apply(ProbabilityDistribution<A> a, ProbabilityDistribution<Function<A, B>> f) {
        return () -> f.sample().apply(a.sample());
    }

    public static <A> ProbabilityDistribution<A> join(ProbabilityDistribution<ProbabilityDistribution<A>> a) {
        return () -> a.sample().sample();
    }

    // GENERATED CODE START
    // Supplemental methods generated by generate_monad_methods.py on 2024-09-04.
    
    public static <A, B> Function<ProbabilityDistribution<A>, ProbabilityDistribution<B>> apply(ProbabilityDistribution<Function<A, B>> f) {
      return a -> apply(a, f);
    }
    
    public static <A, B> ProbabilityDistribution<B> map(ProbabilityDistribution<A> a, Function<A, B> f) {
      return apply(a, pure(f));
    }
    
    public static <A, B> Function<ProbabilityDistribution<A>, ProbabilityDistribution<B>> map(Function<A, B> f) {
      return apply(pure(f));
    }
    
    public static <A, B> ProbabilityDistribution<B> bind(ProbabilityDistribution<A> a, Function<A, ProbabilityDistribution<B>> f) {
      return join(map(a, f));
    }
    
    public static <A, B> Function<ProbabilityDistribution<A>, ProbabilityDistribution<B>> bind(Function<A, ProbabilityDistribution<B>> f) {
      return a -> bind(a, f);
    }
    
    public static <A, B, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, BiFunction<A, B, Result> function) {
      return map(a, b, curry(function));
    }
    
    public static <A, B, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, Function<A, Function<B, Result>> function) {
      return apply(b, map(a, function));
    }
    
    public static <A, B, Result> BiFunction<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<Result>> map(BiFunction<A, B, Result> function) {
      return (a, b) -> map(a, b, function);
    }
    
    public static <A, B, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, BiFunction<A, B, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, Function<A, Function<B, ProbabilityDistribution<Result>>> function) {
      return join(map(a, b, function));
    }
    
    public static <A, B, Result> BiFunction<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<Result>> bind(BiFunction<A, B, ProbabilityDistribution<Result>> function) {
      return (a, b) -> bind(a, b, function);
    }
    
    public static <A, B, C, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, TriFunction<A, B, C, Result> function) {
      return map(a, b, c, curry(function));
    }
    
    public static <A, B, C, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, Function<A, Function<B, Function<C, Result>>> function) {
      return apply(c, map(a, b, function));
    }
    
    public static <A, B, C, Result> TriFunction<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<Result>> map(TriFunction<A, B, C, Result> function) {
      return (a, b, c) -> map(a, b, c, function);
    }
    
    public static <A, B, C, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, TriFunction<A, B, C, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, Function<A, Function<B, Function<C, ProbabilityDistribution<Result>>>> function) {
      return join(map(a, b, c, function));
    }
    
    public static <A, B, C, Result> TriFunction<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<Result>> bind(TriFunction<A, B, C, ProbabilityDistribution<Result>> function) {
      return (a, b, c) -> bind(a, b, c, function);
    }
    
    public static <A, B, C, D, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, Function4<A, B, C, D, Result> function) {
      return map(a, b, c, d, curry(function));
    }
    
    public static <A, B, C, D, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
      return apply(d, map(a, b, c, function));
    }
    
    public static <A, B, C, D, Result> Function4<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<Result>> map(Function4<A, B, C, D, Result> function) {
      return (a, b, c, d) -> map(a, b, c, d, function);
    }
    
    public static <A, B, C, D, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, Function4<A, B, C, D, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, Function<A, Function<B, Function<C, Function<D, ProbabilityDistribution<Result>>>>> function) {
      return join(map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, Result> Function4<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<Result>> bind(Function4<A, B, C, D, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d) -> bind(a, b, c, d, function);
    }
    
    public static <A, B, C, D, E, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, Function5<A, B, C, D, E, Result> function) {
      return map(a, b, c, d, e, curry(function));
    }
    
    public static <A, B, C, D, E, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
      return apply(e, map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<Result>> map(Function5<A, B, C, D, E, Result> function) {
      return (a, b, c, d, e) -> map(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, Function5<A, B, C, D, E, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, ProbabilityDistribution<Result>>>>>> function) {
      return join(map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<Result>> bind(Function5<A, B, C, D, E, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, F, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, Function6<A, B, C, D, E, F, Result> function) {
      return map(a, b, c, d, e, f, curry(function));
    }
    
    public static <A, B, C, D, E, F, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
      return apply(f, map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
      return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, Function6<A, B, C, D, E, F, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, ProbabilityDistribution<Result>>>>>>> function) {
      return join(map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<Result>> bind(Function6<A, B, C, D, E, F, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
      return map(a, b, c, d, e, f, g, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
      return apply(g, map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
      return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, Function7<A, B, C, D, E, F, G, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, ProbabilityDistribution<Result>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<Result>> bind(Function7<A, B, C, D, E, F, G, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
      return map(a, b, c, d, e, f, g, h, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
      return apply(h, map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
      return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, Function8<A, B, C, D, E, F, G, H, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, ProbabilityDistribution<Result>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<Result>> bind(Function8<A, B, C, D, E, F, G, H, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
      return apply(i, map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, Function9<A, B, C, D, E, F, G, H, I, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, ProbabilityDistribution<Result>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
      return apply(j, map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, Function10<A, B, C, D, E, F, G, H, I, J, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, ProbabilityDistribution<Result>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
      return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, ProbabilityDistribution<Result>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
      return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, ProbabilityDistribution<Result>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
      return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, ProbabilityDistribution<Result>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
      return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, ProbabilityDistribution<Result>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
      return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, ProbabilityDistribution<Result>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
      return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, ProbabilityDistribution<Result>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
      return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, ProbabilityDistribution<Result>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
      return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, ProbabilityDistribution<Result>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
      return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<S>, ProbabilityDistribution<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, ProbabilityDistribution<Result>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<S>, ProbabilityDistribution<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, ProbabilityDistribution<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProbabilityDistribution<Result> map(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, ProbabilityDistribution<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
      return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<S>, ProbabilityDistribution<T>, ProbabilityDistribution<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, ProbabilityDistribution<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ProbabilityDistribution<Result>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ProbabilityDistribution<Result> bind(ProbabilityDistribution<A> a, ProbabilityDistribution<B> b, ProbabilityDistribution<C> c, ProbabilityDistribution<D> d, ProbabilityDistribution<E> e, ProbabilityDistribution<F> f, ProbabilityDistribution<G> g, ProbabilityDistribution<H> h, ProbabilityDistribution<I> i, ProbabilityDistribution<J> j, ProbabilityDistribution<K> k, ProbabilityDistribution<L> l, ProbabilityDistribution<M> m, ProbabilityDistribution<N> n, ProbabilityDistribution<O> o, ProbabilityDistribution<P> p, ProbabilityDistribution<Q> q, ProbabilityDistribution<R> r, ProbabilityDistribution<S> s, ProbabilityDistribution<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, ProbabilityDistribution<Result>>>>>>>>>>>>>>>>>>>>> function) {
      return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ProbabilityDistribution<A>, ProbabilityDistribution<B>, ProbabilityDistribution<C>, ProbabilityDistribution<D>, ProbabilityDistribution<E>, ProbabilityDistribution<F>, ProbabilityDistribution<G>, ProbabilityDistribution<H>, ProbabilityDistribution<I>, ProbabilityDistribution<J>, ProbabilityDistribution<K>, ProbabilityDistribution<L>, ProbabilityDistribution<M>, ProbabilityDistribution<N>, ProbabilityDistribution<O>, ProbabilityDistribution<P>, ProbabilityDistribution<Q>, ProbabilityDistribution<R>, ProbabilityDistribution<S>, ProbabilityDistribution<T>, ProbabilityDistribution<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ProbabilityDistribution<Result>> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    // GENERATED CODE END
}
