package gov.nasa.jpl.aerie.contrib.streamline.modeling.random.monads;

import gov.nasa.jpl.aerie.contrib.streamline.core.Resource;
import gov.nasa.jpl.aerie.contrib.streamline.modeling.black_box.Unstructured;
import gov.nasa.jpl.aerie.contrib.streamline.modeling.black_box.monads.UnstructuredResourceApplicative;
import gov.nasa.jpl.aerie.contrib.streamline.modeling.random.ProbabilityDistribution;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

/**
 * Monad A -> Resource&lt;Unstructured&lt;ProbabilityDistribution&lt;A&gt;&gt;&gt;
 * This monad combines continuous state information in the simulation
 * with randomness from a probability distribution.
 * The result is a probability distribution which changes continuously over time.
 */
public class UnstructuredResourceDistributionApplicative {
    private UnstructuredResourceDistributionApplicative() {}

    public static <A> Resource<Unstructured<ProbabilityDistribution<A>>> pure(A a) {
        return UnstructuredResourceApplicative.pure(ProbabilityDistributionMonad.pure(a));
    }

    public static <A, B> Resource<Unstructured<ProbabilityDistribution<B>>> apply(
            Resource<Unstructured<ProbabilityDistribution<A>>> a,
            Resource<Unstructured<ProbabilityDistribution<Function<A, B>>>> f) {
        return UnstructuredResourceApplicative.apply(a, UnstructuredResourceApplicative.map(f, ProbabilityDistributionMonad::apply));
    }

    // Since UnstructuredResourceApplicative is not a monad, we cannot write the two methods below.
    // Unusually, we *are* able to write join, but we aren't able to write distribute.
    // Nevertheless, an applicative still gives us lots of useful functionality for little effort.
    // public static <A> Resource<Unstructured<ProbabilityDistribution<A>>> distribute(ProbabilityDistribution<Resource<Unstructured<A>>> a) {
    //     return () -> UnstructuredDynamicsApplicative.map(a.sample().getDynamics(), ProbabilityDistributionMonad::pure);
    // }

    // public static <A> Resource<Unstructured<ProbabilityDistribution<A>>> join(
    //         Resource<Unstructured<ProbabilityDistribution<Resource<Unstructured<ProbabilityDistribution<A>>>>>> a) {
    //     return UnstructuredResourceApplicative.map(
    //             UnstructuredResourceApplicative.join(UnstructuredResourceApplicative.map(a, UnstructuredResourceDistributionApplicative::distribute)),
    //             ProbabilityDistributionMonad::join);
    // }

    // GENERATED CODE START
    // Supplemental methods generated by generate_monad_methods.py on 2024-09-04.
    
    public static <A, B> Function<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>> apply(Resource<Unstructured<ProbabilityDistribution<Function<A, B>>>> f) {
      return a -> apply(a, f);
    }
    
    public static <A, B> Resource<Unstructured<ProbabilityDistribution<B>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Function<A, B> f) {
      return apply(a, pure(f));
    }
    
    public static <A, B> Function<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>> map(Function<A, B> f) {
      return apply(pure(f));
    }
    
    public static <A, B, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, BiFunction<A, B, Result> function) {
      return map(a, b, curry(function));
    }
    
    public static <A, B, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Function<A, Function<B, Result>> function) {
      return apply(b, map(a, function));
    }
    
    public static <A, B, Result> BiFunction<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(BiFunction<A, B, Result> function) {
      return (a, b) -> map(a, b, function);
    }
    
    public static <A, B, C, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, TriFunction<A, B, C, Result> function) {
      return map(a, b, c, curry(function));
    }
    
    public static <A, B, C, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Function<A, Function<B, Function<C, Result>>> function) {
      return apply(c, map(a, b, function));
    }
    
    public static <A, B, C, Result> TriFunction<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(TriFunction<A, B, C, Result> function) {
      return (a, b, c) -> map(a, b, c, function);
    }
    
    public static <A, B, C, D, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Function4<A, B, C, D, Result> function) {
      return map(a, b, c, d, curry(function));
    }
    
    public static <A, B, C, D, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
      return apply(d, map(a, b, c, function));
    }
    
    public static <A, B, C, D, Result> Function4<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function4<A, B, C, D, Result> function) {
      return (a, b, c, d) -> map(a, b, c, d, function);
    }
    
    public static <A, B, C, D, E, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Function5<A, B, C, D, E, Result> function) {
      return map(a, b, c, d, e, curry(function));
    }
    
    public static <A, B, C, D, E, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
      return apply(e, map(a, b, c, d, function));
    }
    
    public static <A, B, C, D, E, Result> Function5<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function5<A, B, C, D, E, Result> function) {
      return (a, b, c, d, e) -> map(a, b, c, d, e, function);
    }
    
    public static <A, B, C, D, E, F, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Function6<A, B, C, D, E, F, Result> function) {
      return map(a, b, c, d, e, f, curry(function));
    }
    
    public static <A, B, C, D, E, F, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
      return apply(f, map(a, b, c, d, e, function));
    }
    
    public static <A, B, C, D, E, F, Result> Function6<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function6<A, B, C, D, E, F, Result> function) {
      return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
    }
    
    public static <A, B, C, D, E, F, G, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Function7<A, B, C, D, E, F, G, Result> function) {
      return map(a, b, c, d, e, f, g, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
      return apply(g, map(a, b, c, d, e, f, function));
    }
    
    public static <A, B, C, D, E, F, G, Result> Function7<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function7<A, B, C, D, E, F, G, Result> function) {
      return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
      return map(a, b, c, d, e, f, g, h, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
      return apply(h, map(a, b, c, d, e, f, g, function));
    }
    
    public static <A, B, C, D, E, F, G, H, Result> Function8<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
      return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
      return apply(i, map(a, b, c, d, e, f, g, h, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, Result> Function9<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
      return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
      return apply(j, map(a, b, c, d, e, f, g, h, i, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
      return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
      return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
      return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
      return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
      return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
      return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<P>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
      return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<P>>>, Resource<Unstructured<ProbabilityDistribution<Q>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
      return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<P>>>, Resource<Unstructured<ProbabilityDistribution<Q>>>, Resource<Unstructured<ProbabilityDistribution<R>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Resource<Unstructured<ProbabilityDistribution<S>>> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Resource<Unstructured<ProbabilityDistribution<S>>> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
      return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<P>>>, Resource<Unstructured<ProbabilityDistribution<Q>>>, Resource<Unstructured<ProbabilityDistribution<R>>>, Resource<Unstructured<ProbabilityDistribution<S>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Resource<Unstructured<ProbabilityDistribution<S>>> s, Resource<Unstructured<ProbabilityDistribution<T>>> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Unstructured<ProbabilityDistribution<Result>>> map(Resource<Unstructured<ProbabilityDistribution<A>>> a, Resource<Unstructured<ProbabilityDistribution<B>>> b, Resource<Unstructured<ProbabilityDistribution<C>>> c, Resource<Unstructured<ProbabilityDistribution<D>>> d, Resource<Unstructured<ProbabilityDistribution<E>>> e, Resource<Unstructured<ProbabilityDistribution<F>>> f, Resource<Unstructured<ProbabilityDistribution<G>>> g, Resource<Unstructured<ProbabilityDistribution<H>>> h, Resource<Unstructured<ProbabilityDistribution<I>>> i, Resource<Unstructured<ProbabilityDistribution<J>>> j, Resource<Unstructured<ProbabilityDistribution<K>>> k, Resource<Unstructured<ProbabilityDistribution<L>>> l, Resource<Unstructured<ProbabilityDistribution<M>>> m, Resource<Unstructured<ProbabilityDistribution<N>>> n, Resource<Unstructured<ProbabilityDistribution<O>>> o, Resource<Unstructured<ProbabilityDistribution<P>>> p, Resource<Unstructured<ProbabilityDistribution<Q>>> q, Resource<Unstructured<ProbabilityDistribution<R>>> r, Resource<Unstructured<ProbabilityDistribution<S>>> s, Resource<Unstructured<ProbabilityDistribution<T>>> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
      return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
    }
    
    public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Resource<Unstructured<ProbabilityDistribution<A>>>, Resource<Unstructured<ProbabilityDistribution<B>>>, Resource<Unstructured<ProbabilityDistribution<C>>>, Resource<Unstructured<ProbabilityDistribution<D>>>, Resource<Unstructured<ProbabilityDistribution<E>>>, Resource<Unstructured<ProbabilityDistribution<F>>>, Resource<Unstructured<ProbabilityDistribution<G>>>, Resource<Unstructured<ProbabilityDistribution<H>>>, Resource<Unstructured<ProbabilityDistribution<I>>>, Resource<Unstructured<ProbabilityDistribution<J>>>, Resource<Unstructured<ProbabilityDistribution<K>>>, Resource<Unstructured<ProbabilityDistribution<L>>>, Resource<Unstructured<ProbabilityDistribution<M>>>, Resource<Unstructured<ProbabilityDistribution<N>>>, Resource<Unstructured<ProbabilityDistribution<O>>>, Resource<Unstructured<ProbabilityDistribution<P>>>, Resource<Unstructured<ProbabilityDistribution<Q>>>, Resource<Unstructured<ProbabilityDistribution<R>>>, Resource<Unstructured<ProbabilityDistribution<S>>>, Resource<Unstructured<ProbabilityDistribution<T>>>, Resource<Unstructured<ProbabilityDistribution<Result>>>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
      return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
    }
    // GENERATED CODE END
}
